name: Update
on:
  schedule:
    - cron: "0 1 * * *"
  repository_dispatch:
    types: [update]
  workflow_dispatch:

jobs:
  update-buckets:
    name: Check for Updates
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install scoop
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        Invoke-WebRequest https://get.scoop.sh -OutFile get-scoop.ps1
        ./get-scoop.ps1 -RunAsAdmin
        # Workaround for https://github.com/ScoopInstaller/Scoop/issues/4917
        # Should be fixed by https://github.com/ScoopInstaller/Scoop/pull/4960
        # Commenting out the workaround
        ## scoop bucket rm main
        ## scoop bucket add main
        # End workaround
        scoop update
    - name: Update bucket
      shell: pwsh
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "bot@example.com"
        bin/update.ps1
    # Use this action as `git push` doesn't exit cleanly on Windows.
    # See https://github.community/t/push-to-repository-succeeds-but-getting-error-process-completed-with-exit-code-1/18123
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
