name: Update
on:
  repository_dispatch:
    types: [update]

jobs:
  update-buckets:
    name: Check for Updates
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install scoop
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop update
    - name: Update bucket
      shell: pwsh
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "bot@example.com"
        bin/update.ps1
    # Use this action as `git push` doesn't exit cleanly on Windows.
    # See https://github.community/t/push-to-repository-succeeds-but-getting-error-process-completed-with-exit-code-1/18123
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
